### ISSUE TITLE
Mocking library

### ISSUE THREAD

**Issue by djensen47** [amqp-node/amqplib#39]
For TDD and BDD is would be awesome to have a mocking library like what [nock](https://github.com/pgte/nock) does for http requests. I found one for node-amqp but, obviously, I'd prefer to use amqplib.

**Comment by Uzlopak** [comment]
I use docker-compose for tdd.

rabbitMQ.yml:
```yml
version: "3.2"
services:
  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:3.8-management-alpine
    environment:
        - RABBITMQ_DEFAULT_USER=myuser
        - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
        # AMQP protocol port
        - '5672:5672'
        # HTTP management UI
        - '15672:15672'
    networks:
        - intranet

networks:
  intranet:
    driver: bridge
```

And in package.json:

```
	"scripts": {
		"rabbitmq:start": "sudo docker-compose -f ./spec/rabbitmq.yml up -d && sleep 10",
		"rabbitmq:stop": "sudo docker-compose -f ./spec/rabbitmq.yml down",
		"test": "ts-mocha --recursive './spec/*.ts' --preserve-symlinks --exit"
	},
```

So you can spin up a rabbitmq-instance with docker-compose, run your tests, and then kill the container. 

Pro:
- You are using a real rabbitmq-server, so you dont have to rely on an incomplete in-memory-rabbitmq-server (most of them are lacking features)
- You can easily change the version of the rabbitmq-server in the yml. Thus you can easily test if your code still works with a different version of rabbitmq (before you upgrade rabbitmq)

Contra:
- You have to wait till rabbitmq is started. I expect that it is started after 10 seconds (-> sleep 10)
- Probably not the way to go if you want automated tests, while running the unit tests in a docker build
