### ISSUE TITLE
connection_name does not work

### ISSUE THREAD

**Issue by shwarcu** [amqp-node/amqplib#792]
RabbitMQ version 3.13.7
amqplib version: 0.10.8
NodeJS version: 22.14

Documentation mentions that the connection name can be set 
https://amqp-node.github.io/amqplib/channel_api.html

Example from documentation:
```
amqp.connect('amqp://localhost', {clientProperties: {connection_name: 'myFriendlyName'}});
```
Here is my result using connection string `amqp://guest:guest@localhost:5672`
<img width="1579" alt="Image" src="https://github.com/user-attachments/assets/788208ea-88b7-440b-965d-5c9181558c04" />

I run rabbit using docker compose

```yml
version: '3.8'
services:
  rabbitmq_test:
    container_name: rabbitmq_test
    image: rabbitmq:3-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_test:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq_test:
    driver: local

```
